## Find the best point from all the best points got from 9 Algorithms.

In [5]:
import numpy as np

OP_9 = np.array([
    [2.30000000e+01, 3.00000000e+00, 4.92145592e+02, 8.77294924e-03]
    , [3.30000000e+01, 3.00000000e+00, 4.98291053e+02, 1.18579469e-02]
    , [2.20000000e+01, 3.00000000e+00, 4.84345085e+02, 1.01279039e-02]
    , [1.3000000e+01, 3.0000000e+00, 4.5624425e+02, 7.1520997e-03]
    , [8.00000000e+00, 3.00000000e+00, 4.73192007e+02, 5.99302500e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.10434761e+02, 4.93505502e-03]
    , [1.70000000e+01, 3.00000000e+00, 4.85494462e+02, 3.23247907e-02]
    , [1.40000000e+01, 3.00000000e+00, 4.73487326e+02, 9.60173958e-03]
    , [1.00000000e+00, 2.00000000e+00, 4.71411802e+02, 1.90278204e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.75191403e+02, 1.23561810e-02]
    , [1.30000000e+01, 3.00000000e+00, 2.87006947e+02, 1.70227823e-02]
    , [4.00000000e+00, 3.00000000e+00, 2.65033882e+02, 1.01965365e-02]
    , [2.00000000e+01, 3.00000000e+00, 2.85497852e+02, 2.22462173e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.86332235e+02, 8.16079982e-03]
    , [1.80000000e+01, 3.00000000e+00, 2.71928310e+02, 4.97515984e-02]
    , [1.40000000e+01, 3.00000000e+00, 2.77979441e+02, 1.42746241e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.70027110e+02, 4.45530175e-02]
    , [9.00000000e+00, 3.00000000e+00, 2.72024818e+02, 1.24597290e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.06059829e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.04595807e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.06302836e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.10748481e+02, 1.52560630e-02]
    , [1.10000000e+01, 3.00000000e+00, 2.10961792e+02, 3.31860812e-02]
    , [8.00000000e+00, 3.00000000e+00, 2.06142298e+02, 2.23830551e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.07267268e+02, 2.98399242e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.09089883e+02, 1.52398778e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.12688240e+02, 1.77702323e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.02367818e+02, 1.12453575e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.15461420e+02, 1.00614143e-02]
    , [8.00000000e+00, 3.00000000e+00, 2.07051256e+02, 1.39450769e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.98620028e+02, 1.27323788e-02]
    , [1.60000000e+01, 3.00000000e+00, 2.09917317e+02, 1.58696443e-02]
    , [1.20000000e+01, 3.00000000e+00, 2.15330899e+02, 3.18228132e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.07705071e+02, 1.63545917e-02]
    , [7.00000000e+00, 3.00000000e+00, 2.12043358e+02, 1.34067604e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.04791236e+02, 2.26400126e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.15472842e+02, 1.85863844e-02]
    , [6.00000000e+00, 3.00000000e+00, 1.15151371e+02, 3.03813158e-02]
    , [5.00000000e+00, 3.00000000e+00, 1.15085675e+02, 2.65890261e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.13815765e+02, 2.65890261e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13815765e+02, 1.52605613e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.15659062e+02, 1.52605613e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.29629221e+02, 1.31232371e-02]
    , [4.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.76362070e-02]
    , [4.00000000e+00, 3.00000000e+00, 1.29132677e+02, 1.76103761e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.27896063e+02, 1.76103761e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.29629221e+02, 1.49639521e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.62914541e+02, 1.02156214e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.62197844e+02, 9.92124368e-03]
    , [2.00000000e+00, 3.00000000e+00, 1.77085920e+02, 9.69692326e-03]
    , [3.00000000e+00, 3.00000000e+00, 1.69301207e+02, 1.61857911e-02]
    , [9.00000000e+00, 3.00000000e+00, 1.66311454e+02, 2.40019638e-02]
    , [1.10000000e+01, 3.00000000e+00, 1.69295953e+02, 4.23227762e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.67801379e+02, 1.60822135e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.62483088e+02, 2.20867961e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.67068432e+02, 1.75446719e-02]
    , [2.00000000e+00, 3.00000000e+00, 3.91472830e+02, 5.73660851e-03]
    , [1.70000000e+01, 3.00000000e+00, 3.98472506e+02, 9.62586656e-03]
    , [6.00000000e+00, 3.00000000e+00, 3.82543673e+02, 5.87567798e-03]
    , [2.00000000e+00, 3.00000000e+00, 4.18507240e+02, 4.01196226e-03]
    , [1.00000000e+01, 3.00000000e+00, 4.07040819e+02, 2.54450172e-02]
    , [2.10000000e+01, 3.00000000e+00, 4.02773953e+02, 3.65377187e-02]
    , [2.00000000e+01, 3.00000000e+00, 3.98537942e+02, 9.24309173e-03]
    , [9.00000000e+00, 3.00000000e+00, 3.91652113e+02, 9.64667321e-03]
    , [2.00000000e+00, 2.00000000e+00, 3.86702717e+02, 2.58932330e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12667595e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12125553e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12125554e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.66500594e+01, 1.46142136e-02]
    , [2.00000000e+00, 3.00000000e+00, 9.84289531e+01, 2.73371975e-02]
    , [5.00000000e+00, 3.00000000e+00, 7.75058778e+01, 1.70507080e-02]
    , [1.00000000e+00, 2.00000000e+00, 7.38786577e+01, 2.01682911e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.28042438e+01, 1.43493890e-02]
    , [3.00000000e+00, 3.00000000e+00, 7.61826736e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 5.24162573e+01, 9.01129449e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.25824543e+01, 8.81261896e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.24000320e+01, 8.81261896e-03]
    , [3.00000000e+00, 3.00000000e+00, 5.54670162e+01, 1.45748251e-02]
    , [ 2.,          3.,         72.05799059,  0.07371611]
    , [4.00000000e+00, 3.00000000e+00, 5.43734805e+01, 1.46168658e-02]
    , [1.00000000e+00, 2.00000000e+00, 5.30905893e+01, 2.13306247e-02]
    , [2.00000000e+00, 3.00000000e+00, 5.43669134e+01, 1.38429597e-02]
    , [2.0000000e+00, 3.0000000e+00, 5.4968895e+01, 1.1979379e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.56966038e+02, 1.36805721e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.52332532e+02, 1.16263598e-02]
    , [1.00000000e+01, 3.00000000e+00, 2.62192839e+02, 1.47947528e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.64240183e+02, 8.81868906e-03]
    , [1.00000000e+01, 3.00000000e+00, 2.79316034e+02, 3.98396924e-02]
    , [1.70000000e+01, 3.00000000e+00, 2.61674728e+02, 6.41314340e-02]
    , [7.00000000e+00, 3.00000000e+00, 2.65733138e+02, 1.81355995e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.57766010e+02, 4.18866574e-02]
    , [6.00000000e+00, 3.00000000e+00, 2.63880568e+02, 1.40231687e-02]
    , [2.00000000e+00, 3.00000000e+00, 6.61030104e+01, 8.42905792e-03]
    , [2.00000000e+00, 3.00000000e+00, 6.60368817e+01, 8.42905792e-03]
    , [2.00000000e+00, 3.00000000e+00, 6.60933187e+01, 8.42905792e-03]
    , [3.00000000e+00, 3.00000000e+00, 6.75198448e+01, 1.08095444e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.28523824e+01, 3.19409574e-02]
    , [3.00000000e+00, 3.00000000e+00, 6.68408014e+01, 1.11372088e-02]
    , [1.00000000e+00, 2.00000000e+00, 6.67677172e+01, 2.29957316e-02]
    , [2.00000000e+00, 3.00000000e+00, 6.74252958e+01, 1.20198984e-02]
    , [3.00000000e+00, 3.00000000e+00, 6.79462256e+01, 1.09518676e-02]
])

print(OP_9[np.argsort(OP_9[:, 0])])
ideal_9 = np.min(OP_9, axis=0)
print("Ideal Point,", ideal_9)

[[1.00000000e+00 2.00000000e+00 6.67677172e+01 2.29957316e-02]
 [1.00000000e+00 2.00000000e+00 2.70027110e+02 4.45530175e-02]
 [1.00000000e+00 2.00000000e+00 5.30905893e+01 2.13306247e-02]
 [1.00000000e+00 2.00000000e+00 7.38786577e+01 2.01682911e-02]
 [1.00000000e+00 2.00000000e+00 1.62483088e+02 2.20867961e-02]
 [1.00000000e+00 2.00000000e+00 1.27896063e+02 1.76103761e-02]
 [1.00000000e+00 2.00000000e+00 1.13815765e+02 2.65890261e-02]
 [1.00000000e+00 2.00000000e+00 2.04791236e+02 2.26400126e-02]
 [1.00000000e+00 2.00000000e+00 2.07267268e+02 2.98399242e-02]
 [1.00000000e+00 2.00000000e+00 4.71411802e+02 1.90278204e-02]
 [1.00000000e+00 2.00000000e+00 2.57766010e+02 4.18866574e-02]
 [2.00000000e+00 3.00000000e+00 4.18507240e+02 4.01196226e-03]
 [2.00000000e+00 3.00000000e+00 1.13815765e+02 1.52605613e-02]
 [2.00000000e+00 3.00000000e+00 1.15659062e+02 1.52605613e-02]
 [2.00000000e+00 3.00000000e+00 1.13390941e+02 1.27267197e-02]
 [2.00000000e+00 3.00000000e+00 1.27896063e+02 1.312323

## Find the best point from all the best points got from 4 Algorithms.

In [6]:
OP_4 = np.array([
[2.00049131e+00, 3.00026716e+00, 9.34060751e+02, 4.73550988e-03]
, [2.00000000e+00, 1.60000000e+01, 6.21504415e+02, 5.97237461e-03]
, [3.70000000e+01, 2.00000000e+00, 4.60885946e+02, 2.24916674e-02]
, [3.00000000e+00, 1.30000000e+01, 6.07531281e+02, 6.18559476e-03]
, [2.17658408e+00, 3.00018524e+00, 5.66012939e+02, 7.97869833e-03]
, [0.00000000e+00, 4.00000000e+00, 3.77164016e+02, 9.94728974e-03]
, [2.00000000e+00, 2.00000000e+00, 3.31079416e+02, 9.28807644e-03]
, [2.30000000e+01, 2.00000000e+00, 2.70731206e+02, 5.03534046e-02]
, [2.00002250e+00, 3.00120588e+00, 3.57333507e+02, 1.21116142e-02]
, [1.00000000e+00, 0.00000000e+00, 2.66758344e+02, 1.46107486e-02]
, [0.00000000e+00, 0.00000000e+00, 2.43964787e+02, 1.24788344e-02]
, [1.20000000e+01, 2.00000000e+00, 2.04641155e+02, 3.36170844e-02]
, [0.00000000e+00, 3.00000000e+00, 2.62563782e+02, 1.08001838e-02]
, [2.32244364e+00, 3.00003618e+00, 4.57065649e+02, 9.85040400e-03]
, [0.00000000e+00, 5.00000000e+00, 2.80352001e+02, 1.02538125e-02]
, [2.20000000e+01, 2.00000000e+00, 2.05313385e+02, 3.54880241e-02]
, [2.00027407e+00, 3.00105034e+00, 1.61900909e+02, 1.27267197e-02]
, [0.00000000e+00, 0.00000000e+00, 1.15090709e+02, 1.27267197e-02]
, [0.00000000e+00, 0.00000000e+00, 1.16230486e+02, 1.27267197e-02]
, [7.00000000e+00, 2.00000000e+00, 1.12312899e+02, 4.25173310e-02]
, [2.00126617e+00, 3.00396449e+00, 1.74811615e+02, 1.31232371e-02]
, [0.00000000e+00, 0.00000000e+00, 1.27854397e+02, 1.31232371e-02]
, [0.00000000e+00, 0.00000000e+00, 1.27854397e+02, 1.31232371e-02]
, [8.00000000e+00, 2.00000000e+00, 1.26115540e+02, 2.59108321e-02]
, [2.01494202e+00, 3.00047656e+00, 2.76849364e+02, 9.69692326e-03]
, [2.00000000e+00, 0.00000000e+00, 2.03554001e+02, 1.08072179e-02]
, [1.00000000e+00, 1.00000000e+00, 2.25900798e+02, 1.17282333e-02]
, [1.20000000e+01, 2.00000000e+00, 1.67501405e+02, 4.95681728e-02]
, [1.00000000e+00, 1.00000000e+00, 5.04221355e+02, 4.92276639e-03]
, [2.18902806e+00, 3.00003456e+00, 6.98041734e+02, 3.96072190e-03]
, [0.00000000e+00, 1.00000000e+00, 5.01482852e+02, 5.05072946e-03]
, [2.80000000e+01, 2.00000000e+00, 3.85570975e+02, 2.98372657e-02]
, [2.00015425e+00, 3.00009928e+00, 1.49499822e+02, 2.16407958e-02]
, [1.00000000e+00, 0.00000000e+00, 7.75769308e+01, 1.48780249e-02]
, [0.00000000e+00, 0.00000000e+00, 7.29259259e+01, 1.46142136e-02]
, [1.00000000e+01, 2.00000000e+00, 7.83955459e+01, 2.14450400e-02]
, [2.00034443e+00, 3.00255935e+00, 1.00155816e+02, 8.81261896e-03]
, [0.00000000e+00, 0.00000000e+00, 6.73142025e+01, 1.02873841e-02]
, [0.00000000e+00, 0.00000000e+00, 6.60085234e+01, 9.93441245e-03]
, [1.20000000e+01, 2.00000000e+00, 5.81990891e+01, 5.37075658e-02]
, [0.00000000e+00, 3.00000000e+00, 3.30524378e+02, 7.37969373e-03]
, [0.00000000e+00, 6.00000000e+00, 3.28662488e+02, 7.58192168e-03]
, [2.00010853e+00, 3.00013162e+00, 4.92520444e+02, 6.96127994e-03]
, [1.90000000e+01, 2.00000000e+00, 2.55744121e+02, 5.55465266e-02]
, [2.00409209e+00, 3.00039313e+00, 1.05039641e+02, 8.42905792e-03]
, [0.00000000e+00, 0.00000000e+00, 7.04227804e+01, 8.81565161e-03]
, [1.00000000e+00, 0.00000000e+00, 6.83107780e+01, 8.79654841e-03]
, [7.00000000e+00, 2.00000000e+00, 6.96387819e+01, 3.85604750e-02]
])


print(OP_4[np.argsort(OP_4[:, 0])])
ideal_4 = np.min(OP_4, axis=0)
print("Ideal Point:", ideal_4)

[[0.00000000e+00 4.00000000e+00 3.77164016e+02 9.94728974e-03]
 [0.00000000e+00 5.00000000e+00 2.80352001e+02 1.02538125e-02]
 [0.00000000e+00 3.00000000e+00 2.62563782e+02 1.08001838e-02]
 [0.00000000e+00 0.00000000e+00 2.43964787e+02 1.24788344e-02]
 [0.00000000e+00 0.00000000e+00 1.27854397e+02 1.31232371e-02]
 [0.00000000e+00 0.00000000e+00 1.27854397e+02 1.31232371e-02]
 [0.00000000e+00 0.00000000e+00 1.16230486e+02 1.27267197e-02]
 [0.00000000e+00 0.00000000e+00 1.15090709e+02 1.27267197e-02]
 [0.00000000e+00 1.00000000e+00 5.01482852e+02 5.05072946e-03]
 [0.00000000e+00 0.00000000e+00 6.60085234e+01 9.93441245e-03]
 [0.00000000e+00 0.00000000e+00 7.04227804e+01 8.81565161e-03]
 [0.00000000e+00 6.00000000e+00 3.28662488e+02 7.58192168e-03]
 [0.00000000e+00 3.00000000e+00 3.30524378e+02 7.37969373e-03]
 [0.00000000e+00 0.00000000e+00 7.29259259e+01 1.46142136e-02]
 [0.00000000e+00 0.00000000e+00 6.73142025e+01 1.02873841e-02]
 [1.00000000e+00 0.00000000e+00 2.66758344e+02 1.461074

## Find the best point from all the best points got from all Algorithms.

In [7]:
OP_all = np.array([
    [2.30000000e+01, 3.00000000e+00, 4.92145592e+02, 8.77294924e-03]
    , [3.30000000e+01, 3.00000000e+00, 4.98291053e+02, 1.18579469e-02]
    , [2.20000000e+01, 3.00000000e+00, 4.84345085e+02, 1.01279039e-02]
    , [1.3000000e+01, 3.0000000e+00, 4.5624425e+02, 7.1520997e-03]
    , [8.00000000e+00, 3.00000000e+00, 4.73192007e+02, 5.99302500e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.10434761e+02, 4.93505502e-03]
    , [1.70000000e+01, 3.00000000e+00, 4.85494462e+02, 3.23247907e-02]
    , [1.40000000e+01, 3.00000000e+00, 4.73487326e+02, 9.60173958e-03]
    , [1.00000000e+00, 2.00000000e+00, 4.71411802e+02, 1.90278204e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.75191403e+02, 1.23561810e-02]
    , [1.30000000e+01, 3.00000000e+00, 2.87006947e+02, 1.70227823e-02]
    , [4.00000000e+00, 3.00000000e+00, 2.65033882e+02, 1.01965365e-02]
    , [2.00000000e+01, 3.00000000e+00, 2.85497852e+02, 2.22462173e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.86332235e+02, 8.16079982e-03]
    , [1.80000000e+01, 3.00000000e+00, 2.71928310e+02, 4.97515984e-02]
    , [1.40000000e+01, 3.00000000e+00, 2.77979441e+02, 1.42746241e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.70027110e+02, 4.45530175e-02]
    , [9.00000000e+00, 3.00000000e+00, 2.72024818e+02, 1.24597290e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.06059829e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.04595807e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.06302836e+02, 1.21116142e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.10748481e+02, 1.52560630e-02]
    , [1.10000000e+01, 3.00000000e+00, 2.10961792e+02, 3.31860812e-02]
    , [8.00000000e+00, 3.00000000e+00, 2.06142298e+02, 2.23830551e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.07267268e+02, 2.98399242e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.09089883e+02, 1.52398778e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.12688240e+02, 1.77702323e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.02367818e+02, 1.12453575e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.15461420e+02, 1.00614143e-02]
    , [8.00000000e+00, 3.00000000e+00, 2.07051256e+02, 1.39450769e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.98620028e+02, 1.27323788e-02]
    , [1.60000000e+01, 3.00000000e+00, 2.09917317e+02, 1.58696443e-02]
    , [1.20000000e+01, 3.00000000e+00, 2.15330899e+02, 3.18228132e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.07705071e+02, 1.63545917e-02]
    , [7.00000000e+00, 3.00000000e+00, 2.12043358e+02, 1.34067604e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.04791236e+02, 2.26400126e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.15472842e+02, 1.85863844e-02]
    , [6.00000000e+00, 3.00000000e+00, 1.15151371e+02, 3.03813158e-02]
    , [5.00000000e+00, 3.00000000e+00, 1.15085675e+02, 2.65890261e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.13815765e+02, 2.65890261e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13815765e+02, 1.52605613e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.15659062e+02, 1.52605613e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.13390941e+02, 1.27267197e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.29629221e+02, 1.31232371e-02]
    , [4.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.76362070e-02]
    , [4.00000000e+00, 3.00000000e+00, 1.29132677e+02, 1.76103761e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.27896063e+02, 1.76103761e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.27896063e+02, 1.31232371e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.29629221e+02, 1.49639521e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.62914541e+02, 1.02156214e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.62197844e+02, 9.92124368e-03]
    , [2.00000000e+00, 3.00000000e+00, 1.77085920e+02, 9.69692326e-03]
    , [3.00000000e+00, 3.00000000e+00, 1.69301207e+02, 1.61857911e-02]
    , [9.00000000e+00, 3.00000000e+00, 1.66311454e+02, 2.40019638e-02]
    , [1.10000000e+01, 3.00000000e+00, 1.69295953e+02, 4.23227762e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.67801379e+02, 1.60822135e-02]
    , [1.00000000e+00, 2.00000000e+00, 1.62483088e+02, 2.20867961e-02]
    , [2.00000000e+00, 3.00000000e+00, 1.67068432e+02, 1.75446719e-02]
    , [2.00000000e+00, 3.00000000e+00, 3.91472830e+02, 5.73660851e-03]
    , [1.70000000e+01, 3.00000000e+00, 3.98472506e+02, 9.62586656e-03]
    , [6.00000000e+00, 3.00000000e+00, 3.82543673e+02, 5.87567798e-03]
    , [2.00000000e+00, 3.00000000e+00, 4.18507240e+02, 4.01196226e-03]
    , [1.00000000e+01, 3.00000000e+00, 4.07040819e+02, 2.54450172e-02]
    , [2.10000000e+01, 3.00000000e+00, 4.02773953e+02, 3.65377187e-02]
    , [2.00000000e+01, 3.00000000e+00, 3.98537942e+02, 9.24309173e-03]
    , [9.00000000e+00, 3.00000000e+00, 3.91652113e+02, 9.64667321e-03]
    , [2.00000000e+00, 2.00000000e+00, 3.86702717e+02, 2.58932330e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12667595e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12125553e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.12125554e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.66500594e+01, 1.46142136e-02]
    , [2.00000000e+00, 3.00000000e+00, 9.84289531e+01, 2.73371975e-02]
    , [5.00000000e+00, 3.00000000e+00, 7.75058778e+01, 1.70507080e-02]
    , [1.00000000e+00, 2.00000000e+00, 7.38786577e+01, 2.01682911e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.28042438e+01, 1.43493890e-02]
    , [3.00000000e+00, 3.00000000e+00, 7.61826736e+01, 1.43493890e-02]
    , [2.00000000e+00, 3.00000000e+00, 5.24162573e+01, 9.01129449e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.25824543e+01, 8.81261896e-03]
    , [2.00000000e+00, 3.00000000e+00, 5.24000320e+01, 8.81261896e-03]
    , [3.00000000e+00, 3.00000000e+00, 5.54670162e+01, 1.45748251e-02]
    , [ 2.,          3.,         72.05799059,  0.07371611]
    , [4.00000000e+00, 3.00000000e+00, 5.43734805e+01, 1.46168658e-02]
    , [1.00000000e+00, 2.00000000e+00, 5.30905893e+01, 2.13306247e-02]
    , [2.00000000e+00, 3.00000000e+00, 5.43669134e+01, 1.38429597e-02]
    , [2.0000000e+00, 3.0000000e+00, 5.4968895e+01, 1.1979379e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.56966038e+02, 1.36805721e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.52332532e+02, 1.16263598e-02]
    , [1.00000000e+01, 3.00000000e+00, 2.62192839e+02, 1.47947528e-02]
    , [2.00000000e+00, 3.00000000e+00, 2.64240183e+02, 8.81868906e-03]
    , [1.00000000e+01, 3.00000000e+00, 2.79316034e+02, 3.98396924e-02]
    , [1.70000000e+01, 3.00000000e+00, 2.61674728e+02, 6.41314340e-02]
    , [7.00000000e+00, 3.00000000e+00, 2.65733138e+02, 1.81355995e-02]
    , [1.00000000e+00, 2.00000000e+00, 2.57766010e+02, 4.18866574e-02]
    , [6.00000000e+00, 3.00000000e+00, 2.63880568e+02, 1.40231687e-02]
    , [2.00000000e+00, 3.00000000e+00, 6.61030104e+01, 8.42905792e-03]
    , [2.00000000e+00, 3.00000000e+00, 6.60368817e+01, 8.42905792e-03]
    , [2.00000000e+00, 3.00000000e+00, 6.60933187e+01, 8.42905792e-03]
    , [3.00000000e+00, 3.00000000e+00, 6.75198448e+01, 1.08095444e-02]
    , [2.00000000e+00, 3.00000000e+00, 7.28523824e+01, 3.19409574e-02]
    , [3.00000000e+00, 3.00000000e+00, 6.68408014e+01, 1.11372088e-02]
    , [1.00000000e+00, 2.00000000e+00, 6.67677172e+01, 2.29957316e-02]
    , [2.00000000e+00, 3.00000000e+00, 6.74252958e+01, 1.20198984e-02]
    , [3.00000000e+00, 3.00000000e+00, 6.79462256e+01, 1.09518676e-02]
    , [2.00049131e+00, 3.00026716e+00, 9.34060751e+02, 4.73550988e-03]
    , [2.00000000e+00, 1.60000000e+01, 6.21504415e+02, 5.97237461e-03]
    , [3.70000000e+01, 2.00000000e+00, 4.60885946e+02, 2.24916674e-02]
    , [3.00000000e+00, 1.30000000e+01, 6.07531281e+02, 6.18559476e-03]
    , [2.17658408e+00, 3.00018524e+00, 5.66012939e+02, 7.97869833e-03]
    , [0.00000000e+00, 4.00000000e+00, 3.77164016e+02, 9.94728974e-03]
    , [2.00000000e+00, 2.00000000e+00, 3.31079416e+02, 9.28807644e-03]
    , [2.30000000e+01, 2.00000000e+00, 2.70731206e+02, 5.03534046e-02]
    , [2.00002250e+00, 3.00120588e+00, 3.57333507e+02, 1.21116142e-02]
    , [1.00000000e+00, 0.00000000e+00, 2.66758344e+02, 1.46107486e-02]
    , [0.00000000e+00, 0.00000000e+00, 2.43964787e+02, 1.24788344e-02]
    , [1.20000000e+01, 2.00000000e+00, 2.04641155e+02, 3.36170844e-02]
    , [0.00000000e+00, 3.00000000e+00, 2.62563782e+02, 1.08001838e-02]
    , [2.32244364e+00, 3.00003618e+00, 4.57065649e+02, 9.85040400e-03]
    , [0.00000000e+00, 5.00000000e+00, 2.80352001e+02, 1.02538125e-02]
    , [2.20000000e+01, 2.00000000e+00, 2.05313385e+02, 3.54880241e-02]
    , [2.00027407e+00, 3.00105034e+00, 1.61900909e+02, 1.27267197e-02]
    , [0.00000000e+00, 0.00000000e+00, 1.15090709e+02, 1.27267197e-02]
    , [0.00000000e+00, 0.00000000e+00, 1.16230486e+02, 1.27267197e-02]
    , [7.00000000e+00, 2.00000000e+00, 1.12312899e+02, 4.25173310e-02]
    , [2.00126617e+00, 3.00396449e+00, 1.74811615e+02, 1.31232371e-02]
    , [0.00000000e+00, 0.00000000e+00, 1.27854397e+02, 1.31232371e-02]
    , [0.00000000e+00, 0.00000000e+00, 1.27854397e+02, 1.31232371e-02]
    , [8.00000000e+00, 2.00000000e+00, 1.26115540e+02, 2.59108321e-02]
    , [2.01494202e+00, 3.00047656e+00, 2.76849364e+02, 9.69692326e-03]
    , [2.00000000e+00, 0.00000000e+00, 2.03554001e+02, 1.08072179e-02]
    , [1.00000000e+00, 1.00000000e+00, 2.25900798e+02, 1.17282333e-02]
    , [1.20000000e+01, 2.00000000e+00, 1.67501405e+02, 4.95681728e-02]
    , [1.00000000e+00, 1.00000000e+00, 5.04221355e+02, 4.92276639e-03]
    , [2.18902806e+00, 3.00003456e+00, 6.98041734e+02, 3.96072190e-03]
    , [0.00000000e+00, 1.00000000e+00, 5.01482852e+02, 5.05072946e-03]
    , [2.80000000e+01, 2.00000000e+00, 3.85570975e+02, 2.98372657e-02]
    , [2.00015425e+00, 3.00009928e+00, 1.49499822e+02, 2.16407958e-02]
    , [1.00000000e+00, 0.00000000e+00, 7.75769308e+01, 1.48780249e-02]
    , [0.00000000e+00, 0.00000000e+00, 7.29259259e+01, 1.46142136e-02]
    , [1.00000000e+01, 2.00000000e+00, 7.83955459e+01, 2.14450400e-02]
    , [2.00034443e+00, 3.00255935e+00, 1.00155816e+02, 8.81261896e-03]
    , [0.00000000e+00, 0.00000000e+00, 6.73142025e+01, 1.02873841e-02]
    , [0.00000000e+00, 0.00000000e+00, 6.60085234e+01, 9.93441245e-03]
    , [1.20000000e+01, 2.00000000e+00, 5.81990891e+01, 5.37075658e-02]
    , [0.00000000e+00, 3.00000000e+00, 3.30524378e+02, 7.37969373e-03]
    , [0.00000000e+00, 6.00000000e+00, 3.28662488e+02, 7.58192168e-03]
    , [2.00010853e+00, 3.00013162e+00, 4.92520444e+02, 6.96127994e-03]
    , [1.90000000e+01, 2.00000000e+00, 2.55744121e+02, 5.55465266e-02]
    , [2.00409209e+00, 3.00039313e+00, 1.05039641e+02, 8.42905792e-03]
    , [0.00000000e+00, 0.00000000e+00, 7.04227804e+01, 8.81565161e-03]
    , [1.00000000e+00, 0.00000000e+00, 6.83107780e+01, 8.79654841e-03]
    , [7.00000000e+00, 2.00000000e+00, 6.96387819e+01, 3.85604750e-02]
])

print(len(OP_all))
print(OP_all[np.argsort(OP_all[:, 0])])
ideal_all = np.min(OP_all, axis=0)
print("Ideal Point:", ideal_all)

156
[[0.00000000e+00 1.00000000e+00 5.01482852e+02 5.05072946e-03]
 [0.00000000e+00 0.00000000e+00 1.27854397e+02 1.31232371e-02]
 [0.00000000e+00 0.00000000e+00 1.27854397e+02 1.31232371e-02]
 [0.00000000e+00 0.00000000e+00 7.29259259e+01 1.46142136e-02]
 [0.00000000e+00 0.00000000e+00 1.16230486e+02 1.27267197e-02]
 [0.00000000e+00 4.00000000e+00 3.77164016e+02 9.94728974e-03]
 [0.00000000e+00 5.00000000e+00 2.80352001e+02 1.02538125e-02]
 [0.00000000e+00 0.00000000e+00 1.15090709e+02 1.27267197e-02]
 [0.00000000e+00 0.00000000e+00 2.43964787e+02 1.24788344e-02]
 [0.00000000e+00 0.00000000e+00 6.73142025e+01 1.02873841e-02]
 [0.00000000e+00 0.00000000e+00 7.04227804e+01 8.81565161e-03]
 [0.00000000e+00 0.00000000e+00 6.60085234e+01 9.93441245e-03]
 [0.00000000e+00 6.00000000e+00 3.28662488e+02 7.58192168e-03]
 [0.00000000e+00 3.00000000e+00 2.62563782e+02 1.08001838e-02]
 [0.00000000e+00 3.00000000e+00 3.30524378e+02 7.37969373e-03]
 [1.00000000e+00 0.00000000e+00 6.83107780e+01 8.79